- name: Restart MariaDB
  ansible.builtin.service:
    name: mariadb
    state: restarted
  listen: restart_mariadb

- name: Compose up on webserver stack
  ansible.builtin.command: "docker-compose up -d"
  args:
    chdir: "{{ webserver_root }}"
  listen: composeup_webserver

- name: Grab Nextcloud container information
  community.docker.docker_container_info:
    name: "{{ webserver_root | basename }}_nextcloud_1"
  listen: composeup_webserver
  register: nextcloud_info

- name: Wait for Nextcloud to become available
  ansible.builtin.wait_for:
    host: "{{ nextcloud_info.container.NetworkSettings.Networks.traefik.IPAddress }}"
    port: 80
  listen: composeup_webserver

- name: Check Nextcloud status
  ansible.builtin.command: "docker exec --user www-data {{ webserver_root | basename }}_nextcloud_1
            php occ status"
  listen: composeup_webserver
  register: nextcloud_status

- name: Import Nextcloud installation handlers
  ansible.builtin.import_tasks: nextcloud.yml
  listen: composeup_webserver
  when:
    - nextcloud_status.stderr[:26] == "Nextcloud is not installed"
    - nextcloud_autoinstall
