- name: Compose up on webserver stack
  ansible.builtin.command: "docker-compose up -d"
  args:
    chdir: "{{ webserver_root }}"
  listen: composeup_webserver

- name: Restart MariaDB
  ansible.builtin.service:
    name: mariadb
    state: restarted
  listen: restart_mariadb
