- name: Install MariaDB Server
  ansible.builtin.apt:
    name: mariadb-server
    state: present

- name: Create webserver docker-compose directory
  ansible.builtin.file:
    path: "{{ webserver_root }}"
    state: directory
    mode: 0600

- name: Install webserver docker-compose.yml
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "{{ webserver_root }}/docker-compose.yml"
    mode: 0600
  notify: composeup_webserver

- name: Install docker-compose .env
  ansible.builtin.template:
    src: compose-env.j2
    dest: "{{ webserver_root }}/.env"
    mode: 0600
  notify: composeup_webserver
